name: Satori CI - Automated Testing
description: Assert the behavior of your software
icon: check-circle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  satori-cli_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run
        env:
          SATORITOKEN: ${{ secrets.SATORITOKEN }}
        run: |
          pip3 install satori-ci
          satori config token $SATORITOKEN
          satori local ./ --report
