name: "Satori CI - Automated Testing"
description: "Assert the behavior of your software"
branding:
  icon: 'check-circle'
  color: 'white'

runs:
  using: "composite"
  steps:
    - name: Satori CLI
      shell: bash
      run: |
        pip3 install satori-ci
        satori config token "$SATORITOKEN"
        satori local ./ --report
